<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 8/22/2011 11:22:35 AM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Revilla: Lower age coverage of Senior Citizens act pushed  </title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->August 21, 2011<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->LOWER AGE COVERAGE OF SENIOR CITIZENS ACT PUSHED <!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start --><p style="text-align: justify">To further protect the well-being of elders, Senator Ramon Bong Revilla, Jr. today pressed for the lowering of the age coverage of the Senior Citizens Act.</p>
<p style="text-align: justify">The senator filed Senate Bill 2940 that seeks to include 55 years olds as beneficiaries of the Senior Citizens Act.  The law presently covers 60 years old and above. "We want more elders to benefit from the Senior Citizens Act that's why are pushing for this amendment.  This is one way of helping them and acknowledging their efforts in nation-building," said Bong Revilla.</p>
<p style="text-align: justify">According to the lawmaker, it is the duty of the legislators to address to the ever-changing needs of every sector of the society. "We must not be complacent that we have done our part once we have crafted legislation,  We  must  be  vigilant  in  making  sure  that  our  laws  have  successfully  adapted and carry its potency to the present times."</p>
<p style="text-align: justify">Under Senate Bill 2940, citizens age fifty-five years old shall be granted ten percent (10%) discount  from  all  establishments  relative to  utilization  of transportation  services, hotels and  similar  lodging  establishment,  restaurants  and  recreation  centers. Those aged sixty years old and above will still have the existing twenty percent discount privilege.</p>
<p style="text-align: justify">Ten percent discount shall also be given to those aged fifty-five years old in the purchase of medicines.</p>
<p style="text-align: justify">Bong Revilla lamented  that almost  all  sectors of society are  represented  in  Congress,  except  for  the  senior citizens.  "There  is  no  specific  representative  that  voices  their  concerns  and  grievances.  It saddens me that the very people who once ran and headed our society  are  now  reduced  to  the  sidelines,  meek  and  silent  as  the  younger generation takes  over the  reins."</p>
<p style="text-align: justify">He further stressed that existing laws such as the Senior Citizens Act must be reviewed very now and then to conform to the changing times and needs of our citizens.  "For this reason that I believe that we need to revisit the law in order to accommodate citizens that are 55 years old to benefit from its provisions. I urge my fellow legislators to work with me for the immediate passage of this bill. This is one way of continuing the Filipino tradition of caring for our elders," he added.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
