<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 4/6/2015 6:58:28 AM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Recto: Channel SK's P7.7B fund to grassroots anti-hunger projects</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->March 27, 2015<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Channel SK's P7.7B fund to grassroots anti-hunger projects<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify">President Aquino's signing last Wednesday of Republic Act 10656 which moves anew the Sangguniang Kabataan (SK) elections to Oct. 2016 creates the opportunity for channeling P7.7 billion in SK funds toward anti-hunger projects, Sen. Ralph Recto said today.</p>
<p style="text-align: justify">The P7.7 billion represents the SKs' 10 percent share from the P76.7 billion in Internal Revenue Allotment (IRA) barangays will be getting from the national government this year, the senator explained.</p>
<p style="text-align: justify">Recto said the amount can be used by barangays for child-feeding and for other programs that can cut malnutrition rates.</p>
<p style="text-align: justify">"If there's a dividend to be gained from the postponement, then it should come in the form of children's meals," Recto said.</p>
<p style="text-align: justify">Although a series of election postponements has left SKs without officers, the law requiring that 10% of barangay funds be used for youth development programs, however, is still in effect.</p>
<p style="text-align: justify">Even the law signed Wednesday reaffirmed a provision in the previous SK poll postponement law, RA 10632, requiring the Sangguniang Barangay to continue spending the SK fund "solely for youth development programs," the senator pointed out.</p>
<p style="text-align: justify">Recto said Malacanang can "officially encourage the use of SK funds for nutrition projects by ordering the appropriate agencies to issue circulars recommending to barangays that feeding projects be prioritized."</p>
<p style="text-align: justify">"The right of the barangays to select projects will remain. The circular will just provide strong guidance. But even as a 'food for thought', it can mobilize resources to that area," Recto said.</p>
<p style="text-align: justify">Using SK funds for feeding programs in barangay day care centers "will address the two important challenges of promoting literacy and nutrition at the same time," Recto said, in citing one example which can be funded by SK money.</p>
<p style="text-align: justify">"Or it can tackle the supply side by sponsoring the cultivation of vegetable plots, establishment of food banks, or even education drives that will warn against unhealthy food," he said.</p>
<p style="text-align: justify">Doing so would allow SK funds to augment two national programs on cutting child malnutrition, Recto said.</p>
<p style="text-align: justify">Under the 2015 national budget, the DepEd is allocated P2.8 billion to provide meals to 1.93 million undernourished gradeschoolers.</p>
<p style="text-align: justify">The DSWD, on the other hand, will get P3.36 billion for a supplemental feeding program covering 2.5 million two- to five-year olds enrolled in day care centers or are wards of neighborhood associations.</p>
<p style="text-align: justify">Despite increasing huge state allocations, hunger persists, with the Social Weather Station reporting that 3.8 million families, or nearly 18% of total, experienced involuntary hunger in the last quarter of 2014.</p>
<p style="text-align: justify">The most recent National Nutrition Survey paints a disturbing picture of 3 in 10 children 5 years below to be stunted, and 1 in 5 are underweight.</p>
<p style="text-align: justify">Recto said the SK share of P7.7 billion is three times bigger than the 2015 appropriations for the Department of Tourism, twice that of the Department of Trade and Industry, six times that of the Civil Service Commission, and bigger than the combined budget of the 26 state universities and colleges in the Visayas.</p>
<p style="text-align: justify">The IRA represents the 40 percent share of local governments from internal revenues collected by the national government three years before.</p>
<p style="text-align: justify">For this year, total IRA is P389.8, with the 81 provinces getting P91 billion; 144 cities sharing P89.2 billion; 1,478 towns, P132.9 billion; and 41,899 barangays, P76.7 billion.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
