<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 6/15/2015 7:29:37 AM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Problem with underspending ? Give it to the sick, Recto tells gov't</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="/rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="/images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="/">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="/about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="/about/history.asp">History of the Senate</a></p>
<p><a href="/about/symbols%20of%20authority.asp">Symbols of Authority</a></p><p><a href="/about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="/senators/sen18th.asp">18th Congress Senators</a></p><p><a href="/senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="/senators/roll.asp">Roll of Senate President</a></p><p><a href="/senators/composition.asp">Composition of the Senate</a></p><p><a href="/senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="/committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="/committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="/committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="/secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="/secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="/secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="/secretariat/leg.asp">Legislation</a></p><p><a href="/secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="/secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="/secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/lis/leg_sys.aspx?congress=18&type=bill">Bills</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=resolution">Resolutions</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=journal">Journals</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=committee_rpt">Committee Reports</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=republic_act">Republic Acts</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=adopted_res">Adopted Resolutions</a></p>
<p><a href="/18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="/statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="/publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="/publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="/publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="/publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="/publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="/publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/GAD/Bills&Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->June 13, 2015<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Problem with underspending ? Give it to the sick, Recto tells gov't<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify">One effective cure to chronic government underspending is to rechannel a chunk of unutilized funds to health, "specifically aid to the indigent patients because this is one kind of expenditure which will not be bogged by absorptive issues."</p>
<p style="text-align: justify">"Ibigay mo yan sa mga may sakit 'pag hindi ba naman kaagad  magagasta 'yan," Recto said following news that five years into its term, the administration is still grappling with the problem of spending chokepoints.</p>
<p style="text-align: justify">"If you have a problem with wholesale spending, like big-ticket items that don't move, then go into retail," Recto said.</p>
<p style="text-align: justify">"If money is not optimized in projects which are slow-moving, then shift it to the sick who need money for fast-acting cure," Recto said. "Walang absorptive capacity issues sa may sakit."         He said mechanisms are already in place in the Department of Health (DOH), Department of Social Welfare and Development (DSWD) and local governments - which run provincial, district, and municipal hospitals - to handle funds which can be given as direct aid to indigent patients.</p>
<p style="text-align: justify">"Or it can be used to augment the purchase of medicine, needed equipment, or the things needed to run these," he said.</p>
<p style="text-align: justify">"For example, in public hospitals, there's a shortage of chemotherapy drugs, dialysis machines.  In wards, the buy-your-own-dextrose rule prevails," he said.</p>
<p style="text-align: justify">"These are things which are not complicated to procure. It is easier to buy a hospital bed than an MRT train. Or the other alternative is to augment funds that DWSD, DOH and local governments give out as financial assistance to  the sick."</p>
<p style="text-align: justify">"I'm not saying that health should be the default recipient of stuck-up funds. My prescription is to shift maybe a portion of hard-to-obligate allotments to health because there are waiting, deserving, visible recipients who can spend these fast," he said.</p>
<p style="text-align: justify">Public hospitals, he said, are crammed with people in need of government aid. "Kahit mag bed-to-bed rounds ka doon, ang isang milyong piso ng isang social worker ubos kaagad sa laki ng pangangailangan."</p>
<p style="text-align: justify">In the first quarter of the year, government expenditures fell 13 percent of target, following last year's trend of  scrimping which resulted in a budget deficit of P73.1 billion, or about a fourth of what was programmed.</p>
<p style="text-align: justify">In 2013, government underspent by P104 billion, and by P62 billion in 2012.</p>
<p style="text-align: justify">While the public sector  budget for health "commendably reached a historic high this year," at P103 billion, of which P93.1 billion is national government's, on a daily per capita basis, it is still small.</p>
<p style="text-align: justify">"The government health spending this year is about P2.36 per person per day, " Recto said.</p>
<p style="text-align: justify">"Noong 2012, kapag pinagsama ang ginugol ng LGUs, GOCCs at national government, nasa P3.44 per person per day," he said.</p>
<p style="text-align: justify">"Kulang sa dami ng nagkakasakit .  Two Filipinos die every hour from heart disease, five from pneumonia, two from diabetes, and three  from TB. Sa diarrhea, 27 get sick every 60 minutes, while 59 are rushed to ERs for hypertension. Sa dengue, isa bawat labindalawang minuto ang tinatamaan nito," Recto said.</p>
<p style="text-align: justify">"Kaya tuloy sa bawat piso na ginagasta ng isang Pilipino para sa kalusugan, about 19 centavos come from the government, 11 centavos from social insurance and the biggest, about 57 centavos, is from out-of-pocket," he said.</p>
<p style="text-align: justify">"So if government is asking where it can put money which can be spent quickly, then the answer is quite obvious. Give to the sick. And that will also cure underspending," he said.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="/rss/rss_news.aspx"><img src="/images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 23</div><ul><li><a href="/press_release/2020/0623_villanueva1.asp">Statement of Senator Joel Villanueva on the prospects of economic recovery by Q4 2020</a></li>
<li><a href="/press_release/2020/0623_go2.asp">Bong Go urges Executive branch to review health and safety protocols for travels to provinces; protect areas, especially those with low to zero COVID-19 cases</a></li>
<li><a href="/press_release/2020/0623_gordon2.asp">Boost RP’s capability to develop own vaccines – Gordon</a></li>
<li><a href="/press_release/2020/0623_gordon1.asp">Gordon: PRC to put up testing centers in RP’s tourism hubs to ramp up Covid testing</a></li>
<li><a href="/press_release/2020/0623_poe1.asp">Poe: Family backriding in motorcycles to reduce stranded passengers, get people to work faster</a></li>
<li><a href="/press_release/2020/0623_pangilinan1.asp">Pangilinan to govt: Let jeepney, UV Express get back on the road</a></li>
<li><a href="/press_release/2020/0623_go1.asp">Bong Go reminds public to remain vigilant; urges concerned agencies to address the people's needs as COVID-19 crisis continues</a></li>
<li><a href="/press_release/2020/0623_gatchalian1.asp">Boost ICT competitiveness to help spur PH digital economy - Gatchalian</a></li>
<li><a href="/press_release/2020/0623_hontiveros1.asp">Hontiveros files reso urging BIR to suspend tax memo on online sellers</a></li>
<li><a href="/press_release/2020/0623_villar1.asp">Villar to DENR: Bacoor reclamation project threatens protected area, undermines Manila Bay rehabilitation project and will worsen flooding</a></li>
</ul>
	<div class="more">
	<a href="/news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="../job.pdf">Job Openings </a></a>| 
<a href="/contact18thcongress.asp">Contact Info</a> | <a href="/rss.asp">RSS Feeds</a> <a href="/rss.asp">
<img src="/images/feed10.png" alt="RSS icon" /></a> | <a href="/search.aspx">Search</a> | <a href="/sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
