<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 8/11/2015 2:22:56 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Recto: Bill granting tax exemptions to PWDs near Senate OK</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->August 11, 2015<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Bill granting tax exemptions to PWDs nears Senate OK<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify">A bill making the caring of a person with disability (PWD) tax-deductible nears approval in the Senate after it was reported out for floor debates Monday.</p>
<p style="text-align: justify">One of the measure's authors, Senate President Pro-Tempore Ralph G. Recto, explained in his sponsorship speech that the bill confers upon a PWD the status of a dependent for income tax-filing purposes.</p>
<p style="text-align: justify">Under Senate Bill 2890, the "parent, child or legal guardian of a PWD" can claim a tax deduction of P25,000 in his annual income tax, which under the tax code is the same amount granted for every child under 21 years old.</p>
<p style="text-align: justify">The bill being debated in the Senate, however, removes the age limit when applied to a person with a disability.</p>
<p style="text-align: justify">"Kahit 50 years old na 'yan, pwede i-claim as a dependent by the person taking care of him," Recto explained.</p>
<p style="text-align: justify">"So a brother caring for an autistic sibling, or a child who is taking care of a parent who has gone blind, can claim the tax deductible amount of P25,000," Recto said.</p>
<p style="text-align: justify">"We must remove the age limit for a PWD-dependent because caring for him or her should not have an expiry date. Sometimes care extends from cradle to grave," Recto stressed in his sponsorship remarks.</p>
<p style="text-align: justify">Recto said the bill is in response "to the reality that millions of families today who have turned their residences into homes for the aged or infirm."</p>
<p style="text-align: justify">"We have a culture which frowns upon the practice of letting strangers care for a parent and even for those who are willing and wealthy enough to buck convention there are few such facilities here," Recto said.</p>
<p style="text-align: justify">Recto conceded that the P25,000 that can be deducted from final tax bill "barely covers the cost of caring for a PWD. "</p>
<p style="text-align: justify">"It is, however, a good start. We're ending the government embargo on this kind of tax credit," Recto said.</p>
<p style="text-align: justify">Recto said the tax exemption for PWDs must be partnered "with increased spending for PWDs."</p>
<p style="text-align: justify">"Helping PWDs require initiatives in both the revenue and appropriations side," Recto said in urging his colleagues "to install more and wider accessibility ramps to the national budget."</p>
<p style="text-align: justify">He called for the expansion of PWD programs "like opening up of more special education schools, earmarking the supply of school furniture to PWD co-ops, the hiring of more abled disabled, making all roads comply with accessibility laws."</p>
<p style="text-align: justify">According to the 2010 Census of Population and Housing released in 2013, the Philippines has 1.443 million PWDs, or 1.57 percent of the country's total.</p>
<p style="text-align: justify">However, Recto explained that this number "is a lowball figure" as it excludes PWDs living on the streets, institutionalized in hospitals, or held in detention centers.</p>
<p style="text-align: justify">"They are in the shadows. They have fallen through the cracks. This is the reason why we must also improve our registration system," said Recto.</p>
<p style="text-align: justify">He noted that only "348,766 of the total counted PWD have IDs as of 2013. Only one-third has the documentary proof required by establishments to grant them the said discounts and exemptions."</p>
<p style="text-align: justify">Recto hopes that this initiative would be passed by both houses before the last session of the 15th Congress adjourns in December for a prolonged election break.</p>
<p style="text-align: justify">"So let this bill and other budget initiatives be just our continuing amortization of the huge debt we owe them as we vow to increase our subsequent payments," he said</p>
<p style="text-align: justify">"We should do all of the above because it has been said that the worst kind of disability is being paralyzed from coming to the aid of those who need help," Recto said.</p>
<p style="text-align: justify">The other authors of the measure are Senators Sonny Angara, Bam Aquino, Loren Legarda and Nancy Binay.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
