<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 8/26/2015 4:42:36 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Sponsorship Speech of Senator Cynthia Villar</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="/rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="/images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="/">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="/about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="/about/history.asp">History of the Senate</a></p>
<p><a href="/about/symbols%20of%20authority.asp">Symbols of Authority</a></p><p><a href="/about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="/senators/sen18th.asp">18th Congress Senators</a></p><p><a href="/senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="/senators/roll.asp">Roll of Senate President</a></p><p><a href="/senators/composition.asp">Composition of the Senate</a></p><p><a href="/senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="/committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="/committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="/committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="/secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="/secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="/secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="/secretariat/leg.asp">Legislation</a></p><p><a href="/secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="/secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="/secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/lis/leg_sys.aspx?congress=18&type=bill">Bills</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=resolution">Resolutions</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=journal">Journals</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=committee_rpt">Committee Reports</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=republic_act">Republic Acts</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=adopted_res">Adopted Resolutions</a></p>
<p><a href="/18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="/statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="/publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="/publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="/publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="/publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="/publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="/publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/GAD/Bills&Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->August 26, 2015<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Sponsorship Speech of Senator Cynthia Villar<!-- NewsTitle.end --></span>
<br /><span class="PRSub"><!-- NewsTitleSub.start -->Committee Report No. 213 
<br />
August 26, 2015<!-- NewsTitleSub.end--></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify; text-indent: 25px">	Mr. President, my fellow senators. I stand here today to sponsor Committee Report 213, submitted jointly by the Committee on Government Corporations and Public Enterprises, and the Committee on Labor, Employment and Human Resources.</p>
<p style="text-align: justify; text-indent: 25px">	The said committee report covers Senate bills  seeking the increase in the monthly pension under the Social Security System (SSS) by two thousand pesos (PhP2,000) across the board, amending for the purpose Section 12 of Republic Act No. 1161, as amended, otherwise known as the 'Social Security Act of 1997'. These are Senate Bill Nos. 2879, 2888, 451, 220, 15, and 1498 authored by this representation and Senators Guingona, Recto, Ejercito, Marcos, and Estrada respectively. Senator Trillanes has requested to be co-author of the bill I authored (S.B. 2879)</p>
<p style="text-align: justify; text-indent: 25px">	It also covers House Bill No. 5842 (as per Committee Report No. 763) or an act mandating a two-thousand-peso (PhP2,000) across-the-board increase in the monthly pension with corresponding adjustment on the minimum monthly pension under the Social Security System, amending for the purpose Section 12 of R. A. No. 1161, as amended, otherwise known as the "Social Security Act of 1997", authored by Representatives Colmenares, Zarate, Villar, Sacdalan, Primicias-Agabas, Paez, Guanlao, Masongsong, Paquiz and Tinio.</p>
<p style="text-align: justify; text-indent: 25px">	Our committees, Mr. President, recommend that House Bill No. 5842, taking into consideration the earlier mentioned Senate bills, under Committee Report 213 to be adopted without amendment.</p>
<p style="text-align: justify; text-indent: 25px">	Mr. President, esteemed colleagues, it has been said (by Mahatma Gandhi) that "a nation's greatness is measured by how it treats its weakest members". Let me paraphrase it to say that I believe that the effectiveness and responsiveness of a social security system is best measured by how well it provides for its retired members (the pensioners). Who, after all (for a decade or two), were contributing members.</p>
<p style="text-align: justify; text-indent: 25px">	Lest we forget, SSS was created to establish, develop, promote and perfect a sound and viable tax-exempt social security service suitable to the needs of the people throughout the Philippines which shall promote social justice and provide meaningful protection to members and their beneficiaries against the hazards of disability, sickness, maternity, old age, death, and other contingencies resulting in loss of income or financial burden.</p>
<p style="text-align: justify; text-indent: 25px">	The Social Security legislation provides for monthly pensions of retirees. The minimum pension is one thousand two hundred pesos (P1,200) for members with at least ten (10) credited years of service and two thousand four hundred pesos (P2,400) for those with twenty (20) credited years of service. The minimum monthly pension under this law was adjusted several times through legislation or other issuance for it to be as much as possible adequate for retirees to face the rising costs of living.</p>
<p style="text-align: justify; text-indent: 25px">	The latest amendment of Section 12 was under R.A. No. 8282, enacted in 1997.   It has thus been 18 years since the Social Security Law was amended. And there is no doubt that since then, the cost of living being faced by pensioners has risen. As such, there is an urgent need to amend the law, at least with respect to the amount of the monthly pension being received by the retirees.</p>
<p style="text-align: justify; text-indent: 25px">	While the SSS has provided a five percent across the board pension increase for its retired members in 2014, it is admitted that such five percent increase is definitely inadequate and not sufficient to cover the rising cost of living for the past 18 years.</p>
<p style="text-align: justify; text-indent: 25px">	In view of the social justice thrust of our Constitution, and in order to adequately provide for the well-being of our country's retirees, adjustment of their pension is thus long overdue.</p>
<p style="text-align: justify; text-indent: 25px">	The monthly poverty threshold for a family of five is an average income of PhP8,000 per month (as per the latest data from National Statistical Coordination Board). This amount is enough to cover a single family's basic food and non-food needs. Poverty threshold refers to the minimum income a family or individual must earn in order to be considered "not poor".</p>
<p style="text-align: justify; text-indent: 25px">	Having said that, I don't think that the basis for which SSS was established--that of promoting social justice and providing meaningful protection to its members and their beneficiaries against the hazards of old age, loss of income among others--is at work.</p>
<p style="text-align: justify; text-indent: 25px">	Kasi sa tinatanggap na monthly pension ng ating mga retiradong manggagawa na minimum of between 1,200 and 2,400 pesos, mabibilang sila sa mga Pilipinong living below the poverty line. In fact, kahit na dagdagan pa ang kanilang monthly pension ng 2,000 pesos ayon sa ating rekomendasyon, hindi pa rin nila malalampasan ang poverty threshold. As such, they will still be labeled as "poor". According to SSS, as of April 2015, the average pension that they are giving their 1.9 million pensioners is 3,169 pesos, which is still below the poverty threshold.</p>
<p style="text-align: justify; text-indent: 25px">	Ibig sabihin, matapos magtrabaho ang mga pribadong manggagawa ng hanggang dalawampung (20) taon, kapag sila ay retirado na, marami sa kanila, na aasa na lang sa monthly pension nila, ay mamumuhay below the poverty line. Medyo nakakalungkot naman ang hahantungan ng mga empleyado sa ating bansa. Hindi rin natin sila masisisi kung bakit sinita nila ang 10 million pesos na bonus ng mga SSS board of directors noong 2013 at sumama ang loob nila ng malaman nila na noong 2009 ay umabot sa 200 million pesos ang retirement packages ng SSS board members. But that is another issue.</p>
<p style="text-align: justify; text-indent: 25px">	Isa pa, Mr. President, ang natatanggap na monthly pension ng mga retirees ay halos comparable lang sa binibigay natin under the Pantawid Pamilyang Pilipino Program o ang tinatawag na conditional cash transfer (CCT) na ang cash grants ay umaabot sa 1,400 pesos a month. I cannot help but compare dahil ang mga pensioners natin ay nagtrabaho sa loob ng isa, dalawa o mahigit pang dekada.  Bakit naman bibigyan ng ganoong halaga lang iyong mga nagtrabaho at nag-retire after working for so many years? Parang medyo unfair naman iyon.</p>
<p style="text-align: justify; text-indent: 25px">	Mapapabilang pa sila sa mga Pilipinong living below the poverty threshold. It is a sad reality that majority of retired workers in our country rely solely on their monthly pension for their upkeep. On a daily basis, it would barely cover for their sustenance. Kulang pa siguro sa pagkain nila iyon. We must also consider that many of them, given their old age, may even have maintenance medicines and special requirements that add to their daily living expenses.</p>
<p style="text-align: justify; text-indent: 25px">	SSS, through its President and CEO, Mr. Emilio De Quiros Jr., clearly stated in our committee hearing, their position on the proposed pension increase. According to him, they "do not oppose the proposed across-the-board increase of 2,000 pesos in pension benefits" because they "are very sensitive to the needs of the pensioners" and that they "have, more or less, clamored over the years for higher pensions".</p>
<p style="text-align: justify; text-indent: 25px">	But, they are concerned about the impact of the proposal to the SSS fund. Currently, SSS fund life is up to 2042. Ibig sabihin, may sapat silang pondo para sa benepisyo at iba pa, hanggang sa taong 2042 o sa loob ng 27 years mula ngayong taon. Sabi ni Mr. De Quiros, kung ipagkakaloob ang 2,000 pesos na across the board increase sa pension, ang SSS fund life will be shortened to until 2029.</p>
<p style="text-align: justify; text-indent: 25px">	SSS is proposing an increase in the contribution rate of its members--from the current 11 percent to 15 percent--to maintain their fund life at 2042. Based on SSS average monthly salary credit of roughly about 9,500 pesos, the contribution will move from 1,045 pesos to 1,425 pesos or a 380-peso increase. If we apply the ratio of two-thirds employer and one-third employee, additional contribution as shown for the average contribution amount, the total of 380-peso increase, the breakdown would be 255 pesos roughly for the employer and 125 pesos for the employee.</p>
<p style="text-align: justify; text-indent: 25px">	The distribution of SSS contribution is roughly two-thirds employer and one-third employee. Pero ang mga self-employed, voluntary contributors at ang mga overseas Filipino workers (OFWs) ay binabayaran ang buong amount ng contribution. Kaya mas mabigat para sa kanila kung tataasan ang SSS contribution.</p>
<p style="text-align: justify; text-indent: 25px">	Thus, we do not agree with SSS that increasing members' contribution by 15 percent is the solution. As my fellow legislators pointed out during our committee hearing, 2029 is still a good 14 years away. They can still come up with creative ways to lengthen their fund life. They have done it before. In 2001, it was pointed out by Rep. Colmenares, the fund life of SSS was only five years or until 2006 only. So, nakagawa sila ng paraan, at naging until 2042 na ngayon.</p>
<p style="text-align: justify; text-indent: 25px">	SSS recommends that it be given the authority to increase the contribution rate to at least 15 percent and allow subsequent increases in the future in order to support the increasing number of pensioners. But SSS has billions of unremitted collections and uncollected premiums. They should at least improve their collection efforts first, before thinking of increasing members' contribution--which seems to be the easiest thing to do for them. Ipapasa na lang lagi sa mga miyembro o contributors. Dapat singilin muna nila ang mga creditors nila na hindi nagbabayad sa kanila, bago sila mag-isip na dagdagan ang singil sa mga ordinaryong empleyado.</p>
<p style="text-align: justify; text-indent: 25px">	I think it's the responsibility of SSS to find more creative ways so it can lengthen the life of SSS fund, but not at the expense of members. They have ample time to work on it.</p>
<p style="text-align: justify; text-indent: 25px">	SSS can also ask for government subsidy, an option that they are more agreeable to also.  If the proposed 2,000-peso increase in pension benefit will be granted, it will cover 1.9 million pensioners; multiplied by 13 months, it will amount to about 49 billion pesos. As a point of comparison, last year, the Pantawid Pamilya Program or CCT proposed a budget amounting to over 62.6 billion pesos.</p>
<p style="text-align: justify; text-indent: 25px">	Mr. President, I think our retired workers or pensioners deserve subsidy from the government, in the same way that the recipients of CCT grants do.  Siguradong-sigurado ito kasi through formal means. Ang mga recipients ay talagang nagtrabaho ng ilang dekada. This is the best way to reward our workers who devoted their productive years in working. Kung yun mga hindi nagtatrabaho ay sina-subsidize natin, dapat din naman siguro na ang mga nagtrabaho at nagserbisyo sa atin ay i-subsidize rin.  Para naman, pag huminto na sila o hindi na nila kayang mag-trabaho ay makapamuhay naman sila ng maayos.</p>
<p style="text-align: justify; text-indent: 25px">	As I have pointed out earlier, even with the proposed 2,000 pesos increase in their monthly pensions, majority of the pensioners will still live below the poverty threshold. And unlike the other poor Filipinos, they will not be eligible for CCT grants, as they will not meet the criteria.</p>
<p style="text-align: justify; text-indent: 25px">	It may not be much, and will not completely lift them out of poverty, but let us provide our pensioners social justice--the very essence of social security. Lest we fail the "moral test of government", which to quote Former US Vice President Hubert Humphrey, "is how the government treats those who are in the twilight of life--the elderly."</p>
<p style="text-align: justify; text-indent: 25px">	Mr. President, esteemed colleagues, I earnestly seek the swift passage of Committee Report No. 213 to grant  two thousand pesos (PhP2,000) across-the-board increase in the monthly pension under the Social Security System. Thank you.</p>

<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="/rss/rss_news.aspx"><img src="/images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 23</div><ul><li><a href="/press_release/2020/0623_villanueva1.asp">Statement of Senator Joel Villanueva on the prospects of economic recovery by Q4 2020</a></li>
<li><a href="/press_release/2020/0623_go2.asp">Bong Go urges Executive branch to review health and safety protocols for travels to provinces; protect areas, especially those with low to zero COVID-19 cases</a></li>
<li><a href="/press_release/2020/0623_gordon2.asp">Boost RP’s capability to develop own vaccines – Gordon</a></li>
<li><a href="/press_release/2020/0623_gordon1.asp">Gordon: PRC to put up testing centers in RP’s tourism hubs to ramp up Covid testing</a></li>
<li><a href="/press_release/2020/0623_poe1.asp">Poe: Family backriding in motorcycles to reduce stranded passengers, get people to work faster</a></li>
<li><a href="/press_release/2020/0623_pangilinan1.asp">Pangilinan to govt: Let jeepney, UV Express get back on the road</a></li>
<li><a href="/press_release/2020/0623_go1.asp">Bong Go reminds public to remain vigilant; urges concerned agencies to address the people's needs as COVID-19 crisis continues</a></li>
<li><a href="/press_release/2020/0623_gatchalian1.asp">Boost ICT competitiveness to help spur PH digital economy - Gatchalian</a></li>
<li><a href="/press_release/2020/0623_hontiveros1.asp">Hontiveros files reso urging BIR to suspend tax memo on online sellers</a></li>
<li><a href="/press_release/2020/0623_villar1.asp">Villar to DENR: Bacoor reclamation project threatens protected area, undermines Manila Bay rehabilitation project and will worsen flooding</a></li>
</ul>
	<div class="more">
	<a href="/news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="../job.pdf">Job Openings </a></a>| 
<a href="/contact18thcongress.asp">Contact Info</a> | <a href="/rss.asp">RSS Feeds</a> <a href="/rss.asp">
<img src="/images/feed10.png" alt="RSS icon" /></a> | <a href="/search.aspx">Search</a> | <a href="/sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
