<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 070201 on 2/19/2007 3:33:23 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Gordon questions legality of Internet voting</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link rel="stylesheet" type="text/css" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link rel="stylesheet" type="text/css" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
   <div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

   <table id="container">
      <tr>
         <td id="content">
Press Release<br /><!-- NewsDate.start -->February 19, 2007<!-- NewsDate.end --><p>
<span class="PRTitle"><!-- NewsTitle.start -->GORDON QUESTIONS LEGALITY OF INTERNET VOTING<!-- NewsTitle.end --></span></p>
<!-- NewsBody.start --><p>Senator Richard J. Gordon today said that he will be calling a Senate hearing tomorrow to inquire into the legality of COMELECs implementation of internet voting for overseas Filipinos. The fact is, there is no law allowing internet voting to be implemented. Why are they so adamant to push internet voting?</p>
<p>Meanwhile, here is as law (Automated Elections Law) that COMELEC is mandated to implement and they down right refuse to do it without even trying, Senator Gordon said.</p>
<p>Senator Gordon explains that internet voting does not have a legal basis and, more importantly, violates the law for lack of essential safeguard or security features, such as a provision for voter verified paper audit trail. But Senator Gordon noted that COMELEC has apparently found a way to implement internet voting for overseas Filipinos by obtaining an exemption from public bidding from the solicitor general. They now plan to use the Spanish company SCYTL for internet voting. Senator Gordon said.</p>
<p>But the law is clearly not on COMELECs side. Senator Gordon explains that internet voting cannot be allowed under the Absentee Voting Law. The law requires that each ballot cast must be placed in a special envelop, otherwise, it cannot be counted. With internet voting, this requirement cannot be possibly satisfied, said Senator Gordon.</p>
<p>According to Gordon, a Senate inquiry will be able to put to rest the questions surrounding the legality and propriety of the COMELECs move to stubbornly pursue and implement internet voting. Among other things, the COMELEC will have to answer questions on the proper safeguards to ensure that internet voting is even a viable option for the Philippine electoral process, Senator Gordon remarked.</p>
<p>While modernization is the way for a free, honest, orderly and credible elections to be a reality in the Philippines , hastily-conceived measures are to be guarded against. Implementing something without a law supporting it is beyond the ambit of any authority granted to the COMELEC by the Constitution. The people, through the Senate, will be informed through this inquiry, Senator Gordon said.</p>
<p>According to Senator Gordon, the stubborn insistence of COMELEC to implement internet voting taken together with its refusal to implement automation in the 2007 polls make for suspicious actions, to say the least.COMELEC insists that that there is no more time to implement the law. But there are machines out there ready to be tested. There are manufacturers willing to do it. There exists a company even willing to do it for free just to prove that their system works. If the COMELEC were serious about automating, they should have made arrangements to modernize the 2007 polls under the present law, with or without the amendments being passed. They never even did that. They left modernization to chance, said Senator Gordon.</p>
<p>Senator Gordon observes that while the COMELEC insists on implementing internet voting despite the lack of a law to back it, it refuses to implement automation in the May 2007 polls. How can they implement something illegal and simultaneously refuse to implement the law? said Senator Gordon.</p>
<p>RA 8437 or the automated elections law has been passed way back in 1993. The new law signed recently by the President contained amendments to the already existing law. COMELEC was with us working on the amendment from the very beginning. There was enough time for them to prepare. And there is still time to implement the law if they only do their duty. But they never even imagined trying to do it. They simply refuse to do it, Senator Gordon said.</p>
<!-- NewsBody.end -->
         </td>
         <td id="sidepane">
         	<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

         </td>
      </tr>
   </table>
   <div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>

</html>
