<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 070801 2005 on 8/14/2007 1:29:42 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - DPWH passes buck to Meralco, Maynilad over delayed CAMANAVA flood control project,...</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link rel="stylesheet" type="text/css" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link rel="stylesheet" type="text/css" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->August 13, 2007<!-- NewsDate.end -->
<p>
<span class="PRTitle"><!-- NewsTitle.start -->DPWH PASSES BUCK TO MERALCO, MAYNILAD OVER DELAYED CAMANAVA FLOOD CONTROL PROJECT, IRKS REVILLA<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start --><p style="text-align: justify; text-indent: 25px">Instead of blaming other parties for delays, the Department of Public Works and Highways (DPWH) should exercise leadership over its various projects nationwide to ensure their timely completion.</p>
<p style="text-align: justify; text-indent: 25px">"Don't pass the buck, take the lead," was Revilla's curt response to a report furnished him by the DPWH blaming Meralco, Maynilad and the local government of Navotas for the delay in the completion of the P3.79 billion CAMANAVA flood control project.</p>
<p style="text-align: justify; text-indent: 25px">"It is unthinkable that issues such as right of way have not been resolved when the project was due to be finished by July this year," said Revilla, Chair of the Senate Committee on Public Works.</p>
<p style="text-align: justify; text-indent: 25px">Revilla said he has received a lot of complaints from affected residents and commuters in the area. The city of Malabon has declared a state of calamity following the floods caused by the two recent typhoons.</p>
<p style="text-align: justify; text-indent: 25px">According to the June monthly progress report on the flood control project, Meralco and Maynilad have both failed to relocate their facilities which impede the construction of the project at the Longos Creek site and Northern Catmon area.</p>
<p style="text-align: justify; text-indent: 25px">The same report said that Navotas City has not issued road closure permits in the Northbay Boulevard and Lapu-lapu Avenue for digging work to start there. Digging operations in the areas were suspended since March this year.</p>
<p style="text-align: justify; text-indent: 25px">"Two years ago I visited the project site and was assured that it will be completed in due time," said Revilla. "Now all we hear are justifications for delay."</p>
<p style="text-align: justify; text-indent: 25px">Revilla said that as of June this year, the project already posted a negative 19.57% slippage or delay in violation of a DPWH policy that no project should go beyond a negative 15% delay.</p>
<p style="text-align: justify; text-indent: 25px">The senator said that the agency should exhaust all its power and resources to force erring parties to comply with the construction policies and schedule.</p>
<p style="text-align: justify; text-indent: 25px">"If these groups are really at fault, then DPWH must make them pay the price for the delay," Revilla added.</p>
<p style="text-align: justify; text-indent: 25px">But Revilla pointed out that according to the June report the contractor, Nishimatsu Construction Company (NCC) of Japan , also blames DPWH for failing to provide the latter full possession of the constructions sites timely.</p>
<p style="text-align: justify; text-indent: 25px">Revilla stressed that the contract between the DPWH and NCC should not only be terminated but the contractor should also be banned from participating in any project bidding due to delayed construction of the CAMANAVA Flood Control Project.</p>
<p style="text-align: justify; text-indent: 25px">"The DPWH cannot wash its hands over the delay. All the issues mentioned in the report still point to a failure in properly supervising and monitoring of the project" the senator said.</p>

<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
