<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 2/7/2012 2:01:33 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Escudero: Transcript of interview after the session</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->February 7, 2012<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Transcript of interview after the session<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify">Yung liability ng prosecution</p>
<p style="text-align: justify">It's up to them pero clearly there was a violation of the secrecy of bank deposits whoever did that is liable and it's up for the relevant agencies of the government kabilang na ang DOJ to do the corresponding investigation. Ang nais ko lang naman sabihin kahapon sapagpayag naming sa pag-isyu ng subpoena hindi naming tinotolerate, pinapayagan o inaadmit ang partisipasyonng senado sa bagay na yan.</p>
<p style="text-align: justify">Acceptable ba yung paliwanag ni Cong. Umali na isang unknown small lady tatanggap sila ng ganoong dokumento?</p>
<p style="text-align: justify">Acceptable man o hindi, kapani-paniwala man o hindi, kung yon ang binanggit nilang kuwento wala kaming rason para pagdudahan yon, pero payo din siguro naman hindi ganoon kasimple yon dahil sa isang abogado hindi tamang tumanggap ng ebidensiya kung saang sulok o kanto lang kung hindi mo naman nalalaman kung ano nilalaman non, dahil baka mamaya pumabor o kumontra sa kanila yon.</p>
<p style="text-align: justify">Yung prosekusyon pinapa-subpoena ngayon ang mga Supreme Court justices</p>
<p style="text-align: justify">We will discuss in a caucus called for the purpose sometime I think next week or later this week, ang isang concern kasi dyan ng ilang kasamahan naming ay yung prinsipyo at konsepto ng separation of powers. Dagdag pa siguro dyan, ang concern din ng iba may rason kung bakit sekreto yung rolyo ikanga o yung deliberasyon sa Supreme Court at sa ibang korte para malayang makapagdiscuss, makapagdeliberate ang mga miyembro ng waalng takot at ng waalng kailangang timbangin. Isang bagay yon na dapat tingnan ng senado at pag-aralan ng husto.</p>
<p style="text-align: justify">Kung ayaw ng iba na ipatawag ang mga justices, ikaw sir personally?</p>
<p style="text-align: justify">Para sa akin kung willing silang, actually ito'y sa pamamagitan ng subpoena pero kung willing silang tumestigo waal naman kaming magagawa para pigilan yon, ang isyu lang naman dito ay iisyuhan ban g subpoena o hindi. Pero kung may justice na willing tumestigo sino ba naman ang makakapigil sa kanya, ang logic lang naman kasi pwede ba naming silang puwersahin kung ayaw nila, pero kung boluntaryo sialng pupunta rito wala kaming magagawa tungkol don.</p>
<p style="text-align: justify">Ilalagay ba sa executive session if ever?</p>
<p style="text-align: justify">Isa yan sa dapat sana naming talakayin kahapon pero hindi natuloy dahil napahaba yung diskusyon kaugnay ng mga bank deposits.</p>
<p style="text-align: justify">Magiging consideration ba kung sub judice pa yung kaso like yung sa... hindi pa final yung ruling doon.</p>
<p style="text-align: justify">Well isa pa yon sa konsiderasyon ng senado tungkol sa bagay nay an pero gaya ng nasabi koi to ay tungkol lang sa pag-isyu ng compulsory process, iabng uasapan kung may boluntaryong dadating dito na testigo at willing magtestify, kung makukumbinse sila ng prosekusyon hindi na kailanagn pang maisyuhan ng subpoena.</p>
<p style="text-align: justify">So Malabo yung pag-isyu ng subpoena dahil don sa separation of power? Ayokong pangunahan, sinasabi ko lamang ito yung mga kunsiderasyon ng ilan sa aming mga kasamahan pero wala pang pasya ang senado tungkol dito.</p>
<p style="text-align: justify">Kayo sir ano ang consideration nyo?</p>
<p style="text-align: justify">Bahagi yon sa concerns na dapat liwanagin at i-air sa panig at parte ko bilang abogado pero wala pa akong final na pasya kung ito ay pagbobotohan ba naming o hindi.</p>
<p style="text-align: justify">Yung mga banks pwede ba silang i-contempt should they fail to comply?</p>
<p style="text-align: justify">Tinalakay naming pansamantala kahapon yan although informally, dahil baka may sapat silang dahilan o rason, particular sa FCDUs ito yung foreign currency denominated units, dahil interpretasyon namin ang batas yung sinasabi naming applicable lamang ito sa foreigner baka may iba silang interpretasyon at pakinggan natin sila sa Miyerkules, bukas, kun ire-raise nga nila yon o hindi, pero tingin ko hindi magiging ganon kagaang ang kamay ng senado sa pagpataw ng contempt dahil nga mayroong legal question at legal issue tungkol sa bagay na ito.</p>
<p style="text-align: justify">Hindi ba may sini-seek for reconsideration ang defense tapos pinapagawang written lang</p>
<p style="text-align: justify">Hindi, niliwanag ko kaya nga tumayo kao kahapon nagraised ako ng point of order, depensa man o prosekusyon hindi pedeng humiling ng reconsideration sa anumang ruling ng chair, dahil ang ruling ng chair ruling na rin ng senado yan, marereconsider lamang yan kung may isang miyembro din ng senado na tumayo at humiling ng botohan o rekonsiderasyon sa nagging desiyon ng presiding officer.</p>
<p style="text-align: justify">So hindi na pedeng mag-MR ang defense panel?</p>
<p style="text-align: justify">Ang defense o ang prosekyson man hidni pwede, naraised ko na rin ito nong una, applicable yan both sa prosekusyon at sa defense, the parties cannot seek a reconsideration based on precedents and practice in other impeachment trials in other parts of the world.</p>
<p style="text-align: justify">Nahirapan ba kahapon ang impeachment court na magdecide tungkol sa mga bangko kaya kayo twice nagcaucus?</p>
<p style="text-align: justify">Actually yung pangalawang caucus tungkol lamang yon sa pagdraft lamang ng order, pina fine tune yung order, nagkaroon na ng paunang desisyon sa taas pero kailangang irebisahin at basahin yung order para maglagay ng kaunting corrections at assurances din doon, na ito ay unique situation, applicable lamang sa impeachment at hindi dapat magresulta dapat ito ng pangamba sa sinumang depositor o investor sa mga bangko na magbibigay-daan ito na bubuksan na lamang ng ganoong kadali ang mag bank deposits. Ito ay unique process, ito ay unique situation at hindi nangangahulugan na mag-aaplay sa iabng sitwasyon. Reaction na hindi pedeng sampahan ng contempt ang mga bangko na hindi magko-comply sa subpoena</p>
<p style="text-align: justify">Yun yung nabanggit ko kanina, at the very least siguro we will afford them time to seek redress regarding this issue at gaya nga nang nasabi ko hindi magiging ganoon kagaan siguro ang kamay ng senado sa pagcontempt kung saka-sakali dahil nga mayroong contentious legal issue kaugnay sa bagay na to, particular tungkol sa foreign deposits.</p>
<p style="text-align: justify">So what's the point kung pwede naman pala nilang tanggihan yon</p>
<p style="text-align: justify">Hindi naman sa pedeng tanggihan, yung subpoena ad testificandum yon ay dapat sundin, yung subpoena duces tecum marahil nandon ang limitasyon so nasa skill na yon, nasa galling nay an ng mga abogado ng magkabialng panig kung paano nila iapaplabas ang nais nialng palabasin. But with the word of caution still on the part of the prosecution kung totoong inabot lang sa kanila yon, kung totoong wala silang kinalaman doon, minsan mahirap tumanggap ng ebidensiyang galign kung saan-saan lang dahil hindi mo alam na kung pain yon o galing yon sa kabilang panig o kung ano ang nilalaman non, sana hindi sila mabulaga sa bagay nay an.</p>
<p style="text-align: justify">May liability ba ang prosecution doon?</p>
<p style="text-align: justify">It's their call, it's not for us to win the case for them, it's not for us to win the case for the defense, it's their call, it's their strategy, it's their tactic that they're free to employ and implement to win their case for themselves.</p>
<p style="text-align: justify">Kung may mga objection yung defense, o kung anumang party, sa kahit anong pagkakataon pwede silang dumulog sa Supreme Court, like sa isyung ito can they ask the Supreme Court to intervene to stop the senate from calling the banks?</p>
<p style="text-align: justify">Ayokong pangunahan ang bagay nay an pero para sa akin, personally hindi ko pa alam ang desisyon ng senado pero personally tungkol sa jurisdiction ng senado at kapangyarihan ng senado sa isang impeachment trial maliwanag sang-ayon din sa sinabi ni Senator Santiago na mas mataas at supreme ang senado dito pero tungkol sa legal issues medyo grey area yon, kung ang senado nga lang ba ang may karapatan na mag-interpret nyan o mag-aapply yung general rule which is it's the Supreme Court that interprets the laws of the land.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
