<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 9/3/2012 5:18:46 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Transcript of Interview of Senate President Juan Ponce Enrile</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="../../rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="http://senate.gov.ph/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="http://senate.gov.ph/scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="../../images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="../../index.html">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="../../about/history.asp">History of the Senate</a></p>
<p><a href="../../about/symbols&#32;of&#32;authority.asp">Symbols of Authority</a></p><p><a href="../../about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../senators/sen18th.asp">18th Congress Senators</a></p><p><a href="../../senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="../../senators/roll.asp">Roll of Senate President</a></p><p><a href="../../senators/composition.asp">Composition of the Senate</a></p><p><a href="../../senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="../../committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="../../images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="../../notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="../../committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="../../secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="../../secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="../../secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="../../secretariat/leg.asp">Legislation</a></p><p><a href="../../secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="../../secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="../../secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=bill">Bills</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=resolution">Resolutions</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=journal">Journals</a></p>
<p><a href="../../lis/leg_sys.aspx?congress=18&amp;type=committee_rpt">Committee Reports</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=republic_act">Republic Acts</a></p>
<p><a href="../../lis/pdf_sys.aspx?congress=18&amp;type=adopted_res">Adopted Resolutions</a></p>
<p><a href="../../18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="../../statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="../../publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="../../publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="../../publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="../../publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="../../publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="../../publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="../../GAD/Bills&amp;Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->September 3, 2012<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Transcript of Interview of Senate President Juan Ponce Enrile<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start --><p style="text-align: justify">On the problems of banana exports</p>
<p style="text-align: justify">Q: Sir, 'yung sa banana exports, sabi niyo po may problema. Ano po 'yun, sir?</p>
<p style="text-align: justify">SP: May problema sila tungkol sa ginagamit nilang oil for cooking (banana chips).</p>
<p style="text-align: justify">Q: Pumunta sila sa inyo, sir, kaya niyo nalaman?</p>
<p style="text-align: justify">SP: Hindi. They saw me in the hotel in Davao. I told them to write me officially a letter.</p>
<p style="text-align: justify">On Sec. Mar Roxas' appointment</p>
<p style="text-align: justify">Q: Sir, nai-submit na ba sa CA 'yung papers ni Sec. Mar Roxas?</p>
<p style="text-align: justify">SP: Wala pa. Dadaan sa akin 'yun. I will endorse it to the Commission. Wala pang dumating.</p>
<p style="text-align: justify">Q: Sir, may information na this morning, na-transmit na ng Palasyo 'yung nomination letter ni Sec. Mar Roxas...</p>
<p style="text-align: justify">SP: I checked this morning wala pa. Kaninang tanghali, during lunchtime I checked whether the papers of the new appointees of the President, nominees, have reached us and I told them to immediately prepare the transmission to the Commission on Appointments, wala pa.</p>
<p style="text-align: justify">Q: Pero sir, kung matanggap within today, kailan po kaya ma-schedule 'yung confirmation?</p>
<p style="text-align: justify">SP: Depende. They'll have to submit their clearances. 'Yun ang Rules. They have to submit their clearances, their statement of assets and liabilities and other documents then it will be published. After the publication, I think one week 'yun or two weeks, then hearing. 'Yung hearing, one day lang 'yun. Immediately, plenary session then maco-confirm namin sila kung wala namang opposition. I do not anticipate any opposition.</p>
<p style="text-align: justify">Q: Sir, pwede po ba na 'yung mga na-submit niyang documents noong DOTC Secretary ay 'yun na rin ang gamitin?</p>
<p style="text-align: justify">SP: Hindi. Kailangan panibago 'yun. New sets. Pwedeng i-submit 'yung mga dati pero kailan ba na-confirm si Secretary Roxas? Another position ito.</p>
<p style="text-align: justify">Q: Sir, may clamor for Secretary Roxas to resign as LP President para raw hindi maapektuhan 'yung integrity ng DILG?</p>
<p style="text-align: justify">SP: There's no need. We cannot impose that on him. He's the President of the party. When President Marcos was running for president the second time, I think, I do not remember anymore but he was the titular head of the Nacionalista Party. You do not expect the ruling administration to get opposition members for the Cabinet. They will have to use their best material for the positions in the Cabinet unless the top technocrats, but that's a political position. It covers all the provinces, all the cities, all the mayors, all the barangay captains all-over the country. These are not members of the Liberal Party. Many of them are opposition local officials.</p>
<p style="text-align: justify">On the Reproductive Health Bill</p>
<p style="text-align: justify">Q: Sir, do you see lengthy debates po talaga?</p>
<p style="text-align: justify">SP: Ang stage ngayon nung RH Bill ay tinatapos ni Tito 'yung kanyang Turno en Contra. So, siguro, wala ng magsasalita. We are going to a period of amendments. Ang una diyan, committee amendments. Mayroon ba silang committee amendments? Kung wala, individual amendments na 'yun.</p>
<p style="text-align: justify">Q: Pero sir, hanggang kailan niyo pa po nakikita 'yung amendments na 'to?</p>
<p style="text-align: justify">SP: Depende kung ano ang mangyayari sa mga amendments? There's no effort in any one of us to delay the proceedings pero gaya ng sinabi ko, doon mo malalaman how many amendments will be presented. Ako, I have my own amendments. So, I will ask for a vote on the amendments. If they will accept my amendments, immediately, I'll keep quiet.</p>
<p style="text-align: justify">Q: Sir, what are the chances na mapagbotohan ito before the end of the 15th Congress?</p>
<p style="text-align: justify">SP: I don't know. I cannot tell you. Chances, timing, I do not know.</p>
<p style="text-align: justify">Q: Sir, reaction lang, sabi ni Senator Pia, 
delaying tactics is in the air...</p>
<p style="text-align: justify">SP: Delaying tactics? Paano magkakaroon ng delaying tactics when we are working in accordance with the Rules. She can make the proper motion if she really wants to hasten it. Then, we will submit it to a vote.</p>
<p style="text-align: justify">Q: Pero sure ba, sir, na hindi siya aabutin hanggang June at mababasura?</p>
<p style="text-align: justify">SP: Hindi naman siguro. Sinabi ko lang 'yun with the presence of many pending issues here gaya ng budget. Budget 'yun. Sin tax pa. Pinag-uusapan namin. Lahat 'yun priority bills. I cannot say how many will be presenting amendments and how soon the amendments will be disposed.</p>
<p style="text-align: justify">On Koko Pimentel and PDP</p>
<p style="text-align: justify">Q: Sir, si Koko Pimentel, hindi na po siya ang acting na President ng PDP, si VP Binay na po. How will this affect the dynamics within UNA?</p>
<p style="text-align: justify">SP: That's internal to them. The coalition has nothing to do with that so that's a matter that should be settled between him and the vice president. Partido ng Masang Pilipino (PMP) is in coation with PDP Laban. These are two separate political parties. They have their own rules, different members. So, if there's a problem within the members, they have to thresh that out but the coalition continues.</p>
<p style="text-align: justify">On Chief Justice Sereno</p>
<p style="text-align: justify">Q: Sir, should the public be worried na 'yung religious beliefs ni CJ Sereno will affect the performance of her duties?</p>
<p style="text-align: justify">SP: We do not anticipate inability to perform duty. The other side of the coin is also true that she will perform her duties well.</p>
<p style="text-align: justify">Q: Hindi issue 'yung religious beliefs, sir?</p>
<p style="text-align: justify">SP: There's no religious test for any position in the government. You can appoint a non-believer as a Chief Justice or a Justice of the Supreme Court. You can appoint a member of the Islamic faith. You can appoint a born again or a member of the Catholic church. You can also appoint a Buddhist if he's qualified. We have religious freedom in this country.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="../../rss/rss_news.aspx"><img src="../../images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Tuesday, June 9</div><ul><li><a href="../2020/0609_sotto1.asp">Sotto: On Tuition Payment Scheme</a></li>
<li><a href="../2020/0609_pangilinan1.asp">Pangilinan seeks Senate probe of fake Facebook accounts</a></li>
<li><a href="../2020/0609_go1.asp">Bong Go reminds public to use social media responsibly; urges DOJ and NBI to crack down on fake news and fake socmed accounts</a></li>
<li><a href="../2020/0609_gordon1.asp">Gordon urges gov't to set a clear policy to contain COVID, conduct massive testing based on WHO recommendation</a></li>
</ul><div class="news_header">Monday, June 8</div><ul><li><a href="../2020/0608_gordon2.asp">Gordon pushes for massive COVID-19 testing for healthcare workers in public and private institutions</a></li>
<li><a href="../2020/0608_go2.asp">Subsequent roll outs of BP2 beneficiaries to begin soon; Bong Go reminds implementers to ensure proper coordination and health protocols are followed</a></li>
<li><a href="../2020/0608_recto1.asp">'No ride, no work; no back ride, no jeepney ride' pushing up joblessness - Recto</a></li>
<li><a href="../2020/0608_villanueva1.asp">Villanueva: Economic recovery plan must prioritize plight of workers</a></li>
<li><a href="../2020/0608_gordon1.asp">Gordon, glad the DoH acted on the release of P1-M assistance for families of fallen medical frontliners</a></li>
<li><a href="../2020/0608_poe1.asp">Grace Poe on transport:</a></li>
</ul>
	<div class="more">
	<a href="../../news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="http://senate.gov.ph/press_release/job.pdf">Job Openings </a></a>| 
<a href="../../contact18thcongress.asp">Contact Info</a> | <a href="../../rss.asp">RSS Feeds</a> <a href="../../rss.asp">
<img src="../../images/feed10.png" alt="RSS icon" /></a> | <a href="../../search.aspx">Search</a> | <a href="../../sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
