<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 3/11/2014 2:07:41 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Women as agents of change by Senator Miriam Defensor Santiago</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="/rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml_body.css" media="all" />
<style type="text/css">
.style1 {
	text-align: center;
}
</style>
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="/images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="/">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="/about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="/about/history.asp">History of the Senate</a></p>
<p><a href="/about/symbols%20of%20authority.asp">Symbols of Authority</a></p><p><a href="/about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="/senators/sen18th.asp">18th Congress Senators</a></p><p><a href="/senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="/senators/roll.asp">Roll of Senate President</a></p><p><a href="/senators/composition.asp">Composition of the Senate</a></p><p><a href="/senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="/committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="/committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="/committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="/secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="/secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="/secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="/secretariat/leg.asp">Legislation</a></p><p><a href="/secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="/secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="/secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/lis/leg_sys.aspx?congress=18&type=bill">Bills</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=resolution">Resolutions</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=journal">Journals</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=committee_rpt">Committee Reports</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=republic_act">Republic Acts</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=adopted_res">Adopted Resolutions</a></p>
<p><a href="/18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="/statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="/publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="/publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="/publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="/publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="/publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="/publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/GAD/Bills&Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->March 11, 2014<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->WOMEN AS AGENTS OF CHANGE <br />
BY SENATOR MIRIAM DEFENSOR SANTIAGO<!-- NewsTitle.end --></span>
<br /><span class="PRSub"><!-- NewsTitleSub.start -->(Guest speaker at the International Women's Day celebration of the International Rice Research Institute, on Tuesday, 11 March 2014, at IRRI Los Ba&ntilde;os, Laguna)<!-- NewsTitleSub.end--></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify"><strong>THE GENDER GAP</strong></p>
<p style="text-align: justify">The Constitution provides the state policy that: "The state recognizes the role of women in nation building, and shall ensure the fundamental equality before the law of women and men."  (Article 2, Section 14).  Further, under the Equal Protection Clause, women's rights are placed in equipoise with men's rights.</p>
<p style="text-align: justify">On the level of international law, the protection of women's rights is found in an impressive and still growing number of treaties among states.  The most basic of these treaties, to which the Philippines is a party, is known as the Convention on the Elimination of all Forms of Discrimination Against Women, or the CEDAW.  It provides that all states-parties shall eliminate discrimination against women in the political and public life of the country.</p>
<p style="text-align: justify">The United Nations has declared certain Millennium Development Goals, or MDGs.  One of the goals is to promote gender equality and to empower women. In numerical terms alone, there is still a wide gender gap between the sexes.  Numerically, half of our high government officials should be women, and half should be men.  And yet the division between the sexes is highly disproportionate in favor of men.  There have been fifteen Philippine presidents, of which only two have been women.  In the Philippine Senate, in the 16th Congress, of 24 senators, only six of us are women.</p>
<p style="text-align: justify">The Civil Service Commission has issued a memorandum circular setting a target of 50-50 representation of women and men in executive positions.  And yet in 2011, the Civil Service Commission found that women occupy only less than one-third of third-level positions in the government; more than one-third in government-owned and controlled corporations; less than twenty percent in local government units; and more than one-third in the judiciary.  Overall, the proportionate share is 1:2 in favor of men holding top posts in the government.</p>
<p style="text-align: justify">The Geneva-based World Economic Forum conducted a 2011 Global Gender Gap ranking.  There were four categories that determined the gender gap.  These are: (1) educational attainment; (2) health and survival; (3) economic participation and opportunity; and (4) political empowerment.</p>
<p style="text-align: justify">In the first category of educational attainment, the Philippines was among the countries that were listed in the first rank, meaning that the number of females who attended elementary to college education is about the same as that of males.  In the second category of health and survival, the Philippines was also placed in the first rank.  This means that in the Philippines, women and men have more or less the same life expectancy, which is affected by various factors such as disease, malnutrition, and violence.</p>
<p style="text-align: justify">But in the third category of economic participation and opportunity, the Philippines ranked only No. 15 because of evident gaps between men and women in terms of work participation, remuneration, and advancement opportunities. And in the fourth category of political empowerment, the Philippines was ranked No.16, because of the disproportionate women-to-men ratio in government positions.</p>
<p style="text-align: justify"><strong>WOMEN AS AGENTS OF CHANGE</strong></p>
<p style="text-align: justify">A.   Women as Agents of Political Change          Research shows that a lawmaker's gender has a distinct impact on policy priorities. This makes it critical that women are present in politics to represent the concerns of women and other marginalized sectors.  When women are empowered as political leaders, countries often experience higher standards of living with positive developments in education, infrastructure, and health care.[1]</p>
<p style="text-align: justify">After languishing in Congress for some 16 years, Republic Act No. 10354, or "The Responsible Parenthood and Reproductive Health Act of 2012," aka RH Law, was signed by President Aquino last 21 December 2012.  As the principal author and co-sponsor of the RH law in the Senate, I saw how our women lawmakers, the medical community, and women's groups fought long and hard to pass this measure. The RH law affirms that reproductive health care is a human right. The people are entitled to demand it from their government, and the government is obligated to provide it to its constituents.</p>
<p style="text-align: justify">However, the RH law remains under an indefinite status quo ante or halt order, pending the Supreme Court's decision on 14 petitions questioning its legality.</p>
<p style="text-align: justify">In the Philippine government, women account for 58.7% of the total 1.31 million government personnel. However, the women are more likely to be technical staff, while the men are likely to be clerks, managers, or executives.</p>
<p style="text-align: justify">We have had female presidents and now we have a female chief justice. But Congress has never had a female Senate President, or a female Speaker. The greater majority in both chambers of Congress has always been men. Possibly, this is one reason why there is so much corruption in Congress.</p>
<p style="text-align: justify">Therefore, in order to correct the numerical mistake of the past, the logic of gender equality dictates that we should elect six more women as Philippine presidents, until we obtain the same number of female presidents as male presidents.  Under this logic, we should elect a woman president in 2016. We should also vote for at least six qualified female candidates in the Senate in 2016, so that eventually we would have 12 male and 12 female senators at the same time.</p>
<p style="text-align: justify">B.    Women as Agents of Economic Change</p>
<p style="text-align: justify">According to statistics, the vast majority of the world's poor are women. Two-thirds of the world's illiterate population are women. While millions of people around the world eat two or three times a day, a significant percentage of women eat only once. Many women even deny themselves that one meal to feed their children.</p>
<p style="text-align: justify">In many countries, women remain economically marginalized. The UN's MDG Report for 2010 indicates that in South Asia and Sub-Saharan Africa, more than 80 percent of women workers are in some form of vulnerable employment, with no benefits or security, low pay, and in many cases, no pay at all.[2]</p>
<p style="text-align: justify">According to an SWS Survey, the incidence of joblessness for women is much higher than that for men. As of August 2012, some 42.5 percent of jobless Filipinos were women and some 19.3 percent were men.</p>
<p style="text-align: justify">And yet, Filipino women are more active in starting a business than men. The Philippines has the least gender gap among business owners in the world, 55% male versus 45% female. This shows that government must fully support women's economic activities as entrepreneurs in terms of market, capital, training, product development.</p>
<p style="text-align: justify">Research shows that empowering women benefits society as a whole. When women are educated and empowered economically, their families become healthier, their children go to school, incomes increase, and communities thrive.</p>
<p style="text-align: justify"><strong>FEMINIZATION OF AGRICULTURE</strong></p>
<p style="text-align: justify">In feminist economics, the feminization of agriculture refers to the measurable increase of women's participation in the agricultural sector, particularly in the developing world. In Asia and sub-Saharan Africa, women contribute at least half of total labor inputs in rice production. In the Philippines, as of October 2010, there are 5 million women laborers and unskilled workers; and 839,000 women farmers, forestry workers, and fisherfolk.</p>
<p style="text-align: justify">While women's role in the agricultural sector continues to grow, women are often poorer than their male counterparts. Their plot sizes are smaller. They have less access to productive resources like education, tools, and seeds; and social connections like credit and market networks.</p>
<p style="text-align: justify">The International Rice Research Institute (IRRI) leads the way in empowering women in the agriculture sector. The IRRI's Training Center has trained 2,450 female scholars.  From 2002 to 2012, the institute has also given 200 women from 26 countries leadership training courses in agricultural research, development, and extension.</p>
<p style="text-align: justify">The Food and Agriculture Organization of the United Nations has stressed the importance of developing rural female farmers organizations to improve the conditions of women in the agriculture sector, and address the larger problem of food insecurity. I salute the important work that Sulo ng Pamayanan, an IRRI group of women leaders, is doing in promoting women's rights in agriculture. The group conducts training in sustainable and income-generating livelihood projects for women to benefit their families and their communities.</p>
<p class="style1">-o0o-</p>
<p class="style1"><strong>ENDNOTES</strong></p>
<p style="text-align: justify">[1] "Women as Agents of Change: Advancing the Role of Women in Politics and Civil Society," statement by Kenneth Wollack, president, National Democratic Institute, before the House Committee on Foreign Affairs Subcommittee on International Organizations, Human Rights and Oversight, 9 June 2010.</p>
<p style="text-align: justify">[2] "Empowering Women to Change the World: What Universities and the UN Can Do," keynote address of UN Women Executive Director Michelle Bachelet, at the 5th Global Colloquium of University Presidents, University of Pennsylvania, 5 April 2011.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="/rss/rss_news.aspx"><img src="/images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Wednesday, June 24</div><ul><li><a href="/press_release/2020/0624_marcosi1.asp">Imee: Change labor advisories to resolve floating status of employees ASAP</a></li>
<li><a href="/press_release/2020/0624_delima1.asp">De Lima calls for gov't transparency in spending COVID-19 response fund</a></li>
<li><a href="/press_release/2020/0624_go1.asp">Bong Go: fast track provision of benefits for centenarians in accordance with the law; prioritize support for the elderly especially amid COVID-19 outbreak</a></li>
<li><a href="/press_release/2020/0624_hontiveros1.asp">Hontiveros urges gov't to prioritize hiring of Pinoys in flagship projects</a></li>
</ul><div class="news_header">Tuesday, June 23</div><ul><li><a href="/press_release/2020/0623_villanueva1.asp">Statement of Senator Joel Villanueva on the prospects of economic recovery by Q4 2020</a></li>
<li><a href="/press_release/2020/0623_go2.asp">Bong Go urges Executive branch to review health and safety protocols for travels to provinces; protect areas, especially those with low to zero COVID-19 cases</a></li>
<li><a href="/press_release/2020/0623_gordon2.asp">Boost RP’s capability to develop own vaccines – Gordon</a></li>
<li><a href="/press_release/2020/0623_gordon1.asp">Gordon: PRC to put up testing centers in RP’s tourism hubs to ramp up Covid testing</a></li>
<li><a href="/press_release/2020/0623_poe1.asp">Poe: Family backriding in motorcycles to reduce stranded passengers, get people to work faster</a></li>
<li><a href="/press_release/2020/0623_pangilinan1.asp">Pangilinan to govt: Let jeepney, UV Express get back on the road</a></li>
</ul>
	<div class="more">
	<a href="/news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="../job.pdf">Job Openings </a></a>| 
<a href="/contact18thcongress.asp">Contact Info</a> | <a href="/rss.asp">RSS Feeds</a> <a href="/rss.asp">
<img src="/images/feed10.png" alt="RSS icon" /></a> | <a href="/search.aspx">Search</a> | <a href="/sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
