<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 9/15/2014 4:23:05 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Angara calls on youth to participate more in nation-building</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="/rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="/images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="/">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="/about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="/about/history.asp">History of the Senate</a></p>
<p><a href="/about/symbols%20of%20authority.asp">Symbols of Authority</a></p><p><a href="/about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="/senators/sen18th.asp">18th Congress Senators</a></p><p><a href="/senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="/senators/roll.asp">Roll of Senate President</a></p><p><a href="/senators/composition.asp">Composition of the Senate</a></p><p><a href="/senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="/committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="/committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="/committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="/secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="/secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="/secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="/secretariat/leg.asp">Legislation</a></p><p><a href="/secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="/secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="/secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/lis/leg_sys.aspx?congress=18&type=bill">Bills</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=resolution">Resolutions</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=journal">Journals</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=committee_rpt">Committee Reports</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=republic_act">Republic Acts</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=adopted_res">Adopted Resolutions</a></p>
<p><a href="/18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="/statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="/publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="/publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="/publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="/publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="/publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="/publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/GAD/Bills&Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->September 15, 2014<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->ANGARA CALLS ON YOUTH TO PARTICIPATE MORE 
<br />
IN NATION-BUILDING<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify">With the growing dissatisfaction with government and increasing disinterest of the youth to participate in democratic activities, Senator Sonny Angara has called on the youth, as future leaders and decision-makers, to be more active in nation-building to attain a more meaningful democracy in the country.</p>
<p style="text-align: justify">Angara has filed a resolution calling on the Senate to join the community of nations and parliaments around the world in commemorating the 7th International Day of Democracy (IDD) on Monday with the theme, "Engaging Youth on Democracy."</p>
<p style="text-align: justify">"This year's observance of the IDD highlights the crucial role of today's young people in building a better world. Totoo nga na ang kabataan ang pag-asa ng bayan buhat ng kanilang talento, kakayanan at potensyal. Marapat na sa kanila natin ituro ang mga prinsipyo ng demokrasya na ating pinahahalagahan," the senator said in his sponsorship speech.</p>
<p style="text-align: justify">At present, we have the largest youth generation in human history with an estimated 1.8 billion youth aged 10 to 24, which is equivalent to a quarter of the world's population.</p>
<p style="text-align: justify">In addition, another quarter of the world population is composed of children under the age of 10.</p>
<p style="text-align: justify">Here in the Philippines, there is a total of 30.4 million Filipino youth aged 15 to 24, which accounted for 31 percent of the total population in 2013.</p>
<p style="text-align: justify">Based on the April 2014 Labor Force Survey, among the three million unemployed Filipinos, half are from the idle youth.</p>
<p style="text-align: justify">"Many young people, in reality, are marginalized and deprived of the opportunities that our globalizing world has to offer. As lawmakers, this is an impelling reminder that the need to promote and protect the well-being of our youth is as urgent now as ever," Angara said.</p>
<p style="text-align: justify">He emphasized the need to continue to work towards universal access to quality education at all levels to provide our youth with the fundamental platform for their participation in the democratic process.</p>
<p style="text-align: justify">"We have made strides in enacting landmark legislation in education and health. However, we need to pursue more measures that will optimize their physical, mental and emotional health so our young Filipinos will grow into strong contributors to our society," added the lawmaker, who is one of the authors of the Kindergarten law and the Universal Healthcare law.</p>
<p style="text-align: justify">Angara further noted that the youth's dissatisfaction with government and disinterest in democratic activities, particularly during elections where there is a low turnout among youth voters, can threaten the future of the country's representative democracy.</p>
<p style="text-align: justify">"As parliamentarians, we should be able to forge a stronger partnership with the Filipino youth if we reach out to them in the language that they understand and respond to, and through their channels. Information and communications technology and the prominence of new media have made it easier for us to gauge and elicit youth opinion on timely issues. We have better access in understanding their needs. We need to imbue among our youth a renewed sense of awareness and enthusiasm to participate in decision-making," said Angara, who is among the most active senators in social media.</p>
<p style="text-align: justify">He added, "We are called to strengthen our dialogue with the youth by being transparent, sincere and accountable, in order to restore their dwindling faith in our nation's institutions and dispel their growing dissatisfaction and detachment in the democratic process."</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="/rss/rss_news.aspx"><img src="/images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Wednesday, June 24</div><ul><li><a href="/press_release/2020/0624_hontiveros1.asp">Hontiveros urges gov't to prioritize hiring of Pinoys in flagship projects</a></li>
</ul><div class="news_header">Tuesday, June 23</div><ul><li><a href="/press_release/2020/0623_villanueva1.asp">Statement of Senator Joel Villanueva on the prospects of economic recovery by Q4 2020</a></li>
<li><a href="/press_release/2020/0623_go2.asp">Bong Go urges Executive branch to review health and safety protocols for travels to provinces; protect areas, especially those with low to zero COVID-19 cases</a></li>
<li><a href="/press_release/2020/0623_gordon2.asp">Boost RP’s capability to develop own vaccines – Gordon</a></li>
<li><a href="/press_release/2020/0623_gordon1.asp">Gordon: PRC to put up testing centers in RP’s tourism hubs to ramp up Covid testing</a></li>
<li><a href="/press_release/2020/0623_poe1.asp">Poe: Family backriding in motorcycles to reduce stranded passengers, get people to work faster</a></li>
<li><a href="/press_release/2020/0623_pangilinan1.asp">Pangilinan to govt: Let jeepney, UV Express get back on the road</a></li>
<li><a href="/press_release/2020/0623_go1.asp">Bong Go reminds public to remain vigilant; urges concerned agencies to address the people's needs as COVID-19 crisis continues</a></li>
<li><a href="/press_release/2020/0623_gatchalian1.asp">Boost ICT competitiveness to help spur PH digital economy - Gatchalian</a></li>
<li><a href="/press_release/2020/0623_hontiveros1.asp">Hontiveros files reso urging BIR to suspend tax memo on online sellers</a></li>
</ul>
	<div class="more">
	<a href="/news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="../job.pdf">Job Openings </a></a>| 
<a href="/contact18thcongress.asp">Contact Info</a> | <a href="/rss.asp">RSS Feeds</a> <a href="/rss.asp">
<img src="/images/feed10.png" alt="RSS icon" /></a> | <a href="/search.aspx">Search</a> | <a href="/sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
