<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- file generated by WebNewsGen 100809 on 10/7/2014 1:55:18 PM -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Press Release - Villar bats for Family Farming</title>
<link rel="alternate" type="application/rss+xml" title="Latest News Feed - Senate of the Philippines" href="/rss/rss_news.aspx" />
<script type="text/javascript" language="javascript" src="/scripts_web/div.js"></script>
<link type="text/css" rel="stylesheet" href="/scripts_web/print.css" media="print" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml.css" media="all" />
<link type="text/css" rel="stylesheet" href="../../scripts_web/xhtml_body.css" media="all" />
</head>

<body>
<div class="xhtml_nav"><img alt="Senate of the Philippines banner" src="/images/website_banner18th.jpg" class="nav_logo" width="800" height="96" /><div id="nav_top">
<table><tr><td><a href="/">Home</a>&nbsp;</td><td>|</td><td><div onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
&nbsp;About&nbsp;</div><div id="nav_About" class="div_hidden" onmouseover="ShowDiv('nav_About');HideSelect();" onmouseout="HideDiv('nav_About');ShowSelect();">
<div class="nav_dropdown"><p><a href="/about/rulesmenu.asp">Rules of the Senate</a></p><p><a href="/about/history.asp">History of the Senate</a></p>
<p><a href="/about/symbols%20of%20authority.asp">Symbols of Authority</a></p><p><a href="/about/legpro.asp">Legislative Process</a></p>
</div></div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
&nbsp;Senators&nbsp;</div><div id="nav_Senators" class="div_hidden" onmouseover="ShowDiv('nav_Senators');HideSelect();" onmouseout="HideDiv('nav_Senators');ShowSelect();">
<div class="nav_dropdown"><p><a href="/senators/sen18th.asp">18th Congress Senators</a></p><p><a href="/senators/senlist.asp">List of Previous Senators</a></p>
<p><a href="/senators/roll.asp">Roll of Senate President</a></p><p><a href="/senators/composition.asp">Composition of the Senate</a></p><p><a href="/senators/terms.asp">Terms of Office and Privileges</a></p>
</div></div></td><td>|</td><td>
<div onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">&nbsp;Committees&nbsp;</div>
<div id="nav_Committees" class="div_hidden" onmouseover="ShowDiv('nav_Committees');HideSelect();" onmouseout="HideDiv('nav_Committees');ShowSelect();">
<div class="nav_dropdown"><p><a href="/committee/ctte_list18th.pdf">Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/adhocctte_list18th.pdf">Oversight/Ad hoc Committee Chairmanship</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/duties.asp">Duties, Power &amp; Jurisdiction</a></p>
<p><a href="/committee/ctte_mem18th.pdf">Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/committee/oversight_mem18th.pdf">Oversight/Ad hoc Committee Directory</a>&nbsp;<img src="/images/pdf1.gif" alt="Adobe PDF Format" width="12" height="12" /></p>
<p><a href="/notice_ctte.asp">Notice of Committee Meetings</a></p><p><a href="/committee/schedwk.asp">Committee Schedule</a></p></div>
</div></td><td>|</td><td><div onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
&nbsp;Secretariat&nbsp;</div><div id="nav_Secretariat" class="div_hidden" onmouseover="ShowDiv('nav_Secretariat');HideSelect();" onmouseout="HideDiv('nav_Secretariat');ShowSelect();">
<div class="nav_dropdown"><p><a href="/secretariat/mission_vision.asp">Vision and Mission</a></p><p><a href="/secretariat/officers.asp">Officers of the Secretariat</a></p><p><a href="/secretariat/osec.asp">Office of the Secretary</a></p>
<p><a href="/secretariat/leg.asp">Legislation</a></p><p><a href="/secretariat/admin.asp">Administration and Financial Services</a></p>
<p><a href="/secretariat/extaffairs.asp">External Affairs and Relations</a></p><p><a href="/secretariat/osaa.asp">Office of the Sergeant-At-Arms</a></p>
</div></div></td><td>| </td>


<td>
<div onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
&nbsp;Legislative Documents&nbsp;</div>
<div id="nav_LegislativeDocuments" class="div_hidden" onmouseover="ShowDiv('nav_LegislativeDocuments');HideSelect();" onmouseout="HideDiv('nav_LegislativeDocuments');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/lis/leg_sys.aspx?congress=18&type=bill">Bills</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=resolution">Resolutions</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=journal">Journals</a></p>
<p><a href="/lis/leg_sys.aspx?congress=18&type=committee_rpt">Committee Reports</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=republic_act">Republic Acts</a></p>
<p><a href="/lis/pdf_sys.aspx?congress=18&type=adopted_res">Adopted Resolutions</a></p>
<p><a href="/18th_congress/treaties_18thcongress.asp">Treaties</a></p>
<p><a href="/statistical.pdf">Statistical Data</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
&nbsp;Publications&nbsp;</div>
<div id="nav_publications" class="div_hidden" onmouseover="ShowDiv('nav_publications');HideSelect();" onmouseout="HideDiv('nav_publications');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/publications/sepo_publications.asp">SEPO Publications</a></p>
<p><a href="/publications/stsro_publications.asp">STSRO Publications</a></p>
<p><a href="/publications/lbrmo_publications.asp">LBRMO Publications</a></p>
<p><a href="/publications/ils_publications.asp">ILS Publications</a></p>
<p><a href="/publications/lrs_publications.asp">LRS Publications</a></p>
<p><a href="/publications/lls_publications.asp">LLS Publications</a></p>
<p><a href="/publications/other_publications.asp">Other Publications</a></p>
</div>
</div>
</td>
<td>|</td>

<td>
<div onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
&nbsp;GAD&nbsp;</div>
<div id="nav_gad" class="div_hidden" onmouseover="ShowDiv('nav_gad');HideSelect();" onmouseout="HideDiv('nav_gad');ShowSelect();">
<div class="nav_dropdown">
<p><a href="/GAD/Bills&Resolutions_GAD18th1st.pdf">Bills and Resolutions Referred to the Committee on Women, Children, Family Relations and Gender Equality (18th Congress 1st Reg. Session)</a></p>
</div>
</div>
</td>
<td>|</td>


<td>&nbsp;<a href="http://www.newsenatebuilding.com">Bagong Senado</a></td></tr></table></div></div>

<table id="container"><tr><td id="content">
Press Release<br />
<!-- NewsDate.start -->October 7, 2014<!-- NewsDate.end -->
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="float:right">
<a class="addthis_button_facebook"> </a>
<a class="addthis_button_twitter"> </a>
<a class="addthis_button_email"> </a>
<a class="addthis_button_print"> </a>
<a class="addthis_button_compact"> </a>
<a class="addthis_counter addthis_bubble_style"> </a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dc7a23848471063"></script>
<!-- AddThis Button END -->
<p style="text-align: center">
<span class="PRTitle"><!-- NewsTitle.start -->Villar bats for Family Farming<!-- NewsTitle.end --></span>
</p>
<!-- NewsBody.start -->
<p style="text-align: justify; text-indent: 25px">SENATOR Cynthia A. Villar called on Filipino families particularly those living in the provinces to indulge in family farming, or planting vegetables and fruits in their own backyard.             Oftentimes, she said that backyard farms or vegetable gardens paved the way for agri-related or farm business enterprises.             "And family farmers are very important in the country's food security and economy," stressed Villar.</p>
<p style="text-align: justify; text-indent: 25px">In fact, she said the United Nations declared 2014 "International year of Family Farming."             Based on official statistics, she said 1.5 billion of people globally are estimated to be involved in family farming in over 500 million small farms worldwide.   Also, 50 percent of food globally is produced by family farmers.</p>
<p style="text-align: justify; text-indent: 25px">"The food security of our country and the world is largely dependent on small farmers. But like what I have said, they belong to the lowest-paid earners," said the senator.</p>
<p style="text-align: justify; text-indent: 25px">Because of this fact, Villar cited the need to help small farmers providing them opportunities for additional sources of income.</p>
<p style="text-align: justify; text-indent: 25px">"We must always remember that the Philippines is an agricultural country, and two-thirds of our population is involved directly or indirectly in the agriculture sector," she said.</p>
<p style="text-align: justify; text-indent: 25px">Despite the availability of modern technology, she lamented that many of the agri-business people have embraced back-to-basics approach.</p>
<p style="text-align: justify; text-indent: 25px">"Their businesses are home or community-based. Many have gone into backyard farming or fruits and vegetable gardening," she said.</p>
<p style="text-align: justify; text-indent: 25px">"In provinces where it is viable, we are also encouraging communities to start their own vegetable gardens," she added.</p>
<p style="text-align: justify; text-indent: 25px">The senator said she regularly gives vegetable garden projects to families affected by recent typhoons in various provinces, most of whom were still living in tents or shelters. She likewise said this kind of agricultural work  is  applicable for returning  Overseas Filipino Workers (OFWs) who live outside Metro Manila.</p>
<p style="text-align: justify; text-indent: 25px">"With a small capital and some plot of land in their backyard, they can start an agribusiness," said Villar, adding that she and her husband, former Senate President Manny Villar have been calling out for a new generation of entrepreneurs, including  agri-preneurs.</p>
<!-- NewsBody.end -->
</td><td id="sidepane">
<div id="sidepane_l2"></div><div class="header_pane">
News <a href="/rss/rss_news.aspx"><img src="/images/feed10.png" alt="Latest News Feed" /></a>
</div>

<div class="sidepane_nav">
<div class="news_header">Wednesday, June 24</div><ul><li><a href="/press_release/2020/0624_hontiveros1.asp">Hontiveros urges gov't to prioritize hiring of Pinoys in flagship projects</a></li>
</ul><div class="news_header">Tuesday, June 23</div><ul><li><a href="/press_release/2020/0623_villanueva1.asp">Statement of Senator Joel Villanueva on the prospects of economic recovery by Q4 2020</a></li>
<li><a href="/press_release/2020/0623_go2.asp">Bong Go urges Executive branch to review health and safety protocols for travels to provinces; protect areas, especially those with low to zero COVID-19 cases</a></li>
<li><a href="/press_release/2020/0623_gordon2.asp">Boost RP’s capability to develop own vaccines – Gordon</a></li>
<li><a href="/press_release/2020/0623_gordon1.asp">Gordon: PRC to put up testing centers in RP’s tourism hubs to ramp up Covid testing</a></li>
<li><a href="/press_release/2020/0623_poe1.asp">Poe: Family backriding in motorcycles to reduce stranded passengers, get people to work faster</a></li>
<li><a href="/press_release/2020/0623_pangilinan1.asp">Pangilinan to govt: Let jeepney, UV Express get back on the road</a></li>
<li><a href="/press_release/2020/0623_go1.asp">Bong Go reminds public to remain vigilant; urges concerned agencies to address the people's needs as COVID-19 crisis continues</a></li>
<li><a href="/press_release/2020/0623_gatchalian1.asp">Boost ICT competitiveness to help spur PH digital economy - Gatchalian</a></li>
<li><a href="/press_release/2020/0623_hontiveros1.asp">Hontiveros files reso urging BIR to suspend tax memo on online sellers</a></li>
</ul>
	<div class="more">
	<a href="/news.asp?year=2020">
	news archives...</a></div>
</div>

</td></tr></table>
<div class="xhtml_nav"><div id="nav_bottom"><table><tr>
	<td style="text-align: left; color: white; width: 381px;">© Senate of the Philippines. All rights reserved.</td>
<td style="text-align: right">
<a href="../job.pdf">Job Openings </a></a>| 
<a href="/contact18thcongress.asp">Contact Info</a> | <a href="/rss.asp">RSS Feeds</a> <a href="/rss.asp">
<img src="/images/feed10.png" alt="RSS icon" /></a> | <a href="/search.aspx">Search</a> | <a href="/sitemap.asp">Site Map</a></td></tr></table></div></div>


</body>
</html>
